# Generated by Django 5.1.4 on 2024-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('package_type', models.CharField(choices=[('family', 'Family'), ('luxury', 'Luxury'), ('honeymoon', 'Honeymoon'), ('adventure', 'Adventure')], max_length=50)),
                ('destinations', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='upload images/')),
                ('status', models.CharField(blank=True, default='Active', max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
