# Generated by Django 5.1.4 on 2025-01-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelagent_app', '0003_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagent_model',
            name='status',
        ),
    ]
