# Generated by Django 5.1.4 on 2024-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_send_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_feedback',
            name='reply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
