# Generated by Django 5.1.4 on 2024-12-23 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_send_feedback_reply_date'),
        ('travelagent_app', '0002_travel_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('name_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('packageid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelagent_app.travel_package')),
            ],
        ),
    ]
