# Generated by Django 5.1.4 on 2024-12-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accountnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
